// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// find_matches
List find_matches(DataFrame DS1, DataFrame DS2, CharacterVector classtype, int KN);
RcppExport SEXP _diffdf_find_matches(SEXP DS1SEXP, SEXP DS2SEXP, SEXP classtypeSEXP, SEXP KNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type DS1(DS1SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type DS2(DS2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type classtype(classtypeSEXP);
    Rcpp::traits::input_parameter< int >::type KN(KNSEXP);
    rcpp_result_gen = Rcpp::wrap(find_matches(DS1, DS2, classtype, KN));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_diffdf_find_matches", (DL_FUNC) &_diffdf_find_matches, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_diffdf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
