# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doublediff <- function(x, y, tolerance, scale = 0) {
    .Call('_diffdf_doublediff', PACKAGE = 'diffdf', x, y, tolerance, scale)
}

stringdiff <- function(x, y) {
    .Call('_diffdf_stringdiff', PACKAGE = 'diffdf', x, y)
}

