# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_matches <- function(DS1, DS2, classtype, KN) {
    .Call('_diffdf_find_matches', PACKAGE = 'diffdf', DS1, DS2, classtype, KN)
}

