


on:
  schedule:
    - cron: '0 4 1,15 * *'
  workflow_dispatch:

name: CRON

jobs:
  r-cmd:
    name: R CMD Check 🧬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        CMDSTAN=/root/.cmdstan
        CMDSTAN_PATH=/root/.cmdstan
        CMDSTANR_NO_VER_CHECK=true
        JMPOST_CACHE_DIR=${{ github.workspace }}/.cache
        JMPOST_FULL_TEST=TRUE
      additional-caches: |
        ${{ github.workspace }}/.cache






