on:
  push:
    branches:    
      - github_actions_release


name: CRAN Checks

jobs:
  rhub:
    runs-on: [ubuntu-latest]
    if:  contains(github.event.head_commit.message, '[cran-checks]')
    strategy:
      matrix:
        rhub: [macos-elcapitan-release, ubuntu-gcc-devel, windows-x86_64-release]
    container:
      image: rocker/verse:latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: rhub checks
        run: |
          Rscript -e "rhub::validate_email(email = '${{ secrets.RHUB_EMAIL }}', token = '${{ secrets.RHUB_TOKEN }}')"
          #Rscript -e "rhub::check(platform = '${{ matrix.rhub }}')"
        
