on:
  push:
    branches:    
      - github_actions_release


name: check_for_cran - Rhub

jobs:
  my_first_job:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        rhub: [macos-elcapitan-release, ubuntu-gcc-devel, windows-x86_64-release]
    container:
      image: rocker/verse:latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: rhub checks
        run: |
          Rscript -e "rhub::validate_email(email = '${{ secrets.RHUB_EMAIL }}', token = '${{ secrets.RHUB_TOKEN }}')"
          Rscrupt -e "rhub::check(platform = '${{ matrix.rhub }}')"
